//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya_7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип прихода.
    /// </summary>
    // *** Start programmer edit section *** (ТипПрихода CustomAttributes)

    // *** End programmer edit section *** (ТипПрихода CustomAttributes)
    public enum ТипПрихода
    {
        
        // *** Start programmer edit section *** (ТипПрихода.1 CustomAttributes)

        // *** End programmer edit section *** (ТипПрихода.1 CustomAttributes)
        [Caption("Реализация товаров")]
        1,
        
        // *** Start programmer edit section *** (ТипПрихода.2 CustomAttributes)

        // *** End programmer edit section *** (ТипПрихода.2 CustomAttributes)
        [Caption("Реализация услуг")]
        2,
    }
}
