//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya_7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товары.
    /// </summary>
    // *** Start programmer edit section *** (Товары CustomAttributes)

    // *** End programmer edit section *** (Товары CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварыE", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    [AssociatedDetailViewAttribute("ТоварыE", "СоставТовара", "СоставТовараE", true, "", "Состав товара", true, new string[] {
            ""})]
    [View("ТоварыL", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    public class Товары : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНаименование;
        
        private double fСтоимость;
        
        private IIS.Sonya_7.DetailArrayOfСоставТовара fСоставТовара;
        
        // *** Start programmer edit section *** (Товары CustomMembers)

        // *** End programmer edit section *** (Товары CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Товары.ID CustomAttributes)

        // *** End programmer edit section *** (Товары.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Товары.ID Get start)

                // *** End programmer edit section *** (Товары.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Товары.ID Get end)

                // *** End programmer edit section *** (Товары.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.ID Set start)

                // *** End programmer edit section *** (Товары.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Товары.ID Set end)

                // *** End programmer edit section *** (Товары.ID Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Наименование CustomAttributes)

        // *** End programmer edit section *** (Товары.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Наименование Get start)

                // *** End programmer edit section *** (Товары.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Товары.Наименование Get end)

                // *** End programmer edit section *** (Товары.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Наименование Set start)

                // *** End programmer edit section *** (Товары.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Товары.Наименование Set end)

                // *** End programmer edit section *** (Товары.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Товары.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Стоимость Get start)

                // *** End programmer edit section *** (Товары.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (Товары.Стоимость Get end)

                // *** End programmer edit section *** (Товары.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Стоимость Set start)

                // *** End programmer edit section *** (Товары.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Товары.Стоимость Set end)

                // *** End programmer edit section *** (Товары.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Товары.
        /// </summary>
        // *** Start programmer edit section *** (Товары.СоставТовара CustomAttributes)

        // *** End programmer edit section *** (Товары.СоставТовара CustomAttributes)
        public virtual IIS.Sonya_7.DetailArrayOfСоставТовара СоставТовара
        {
            get
            {
                // *** Start programmer edit section *** (Товары.СоставТовара Get start)

                // *** End programmer edit section *** (Товары.СоставТовара Get start)
                if ((this.fСоставТовара == null))
                {
                    this.fСоставТовара = new IIS.Sonya_7.DetailArrayOfСоставТовара(this);
                }
                IIS.Sonya_7.DetailArrayOfСоставТовара result = this.fСоставТовара;
                // *** Start programmer edit section *** (Товары.СоставТовара Get end)

                // *** End programmer edit section *** (Товары.СоставТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.СоставТовара Set start)

                // *** End programmer edit section *** (Товары.СоставТовара Set start)
                this.fСоставТовара = value;
                // *** Start programmer edit section *** (Товары.СоставТовара Set end)

                // *** End programmer edit section *** (Товары.СоставТовара Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварыE", typeof(IIS.Sonya_7.Товары));
                }
            }
            
            /// <summary>
            /// "ТоварыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварыL", typeof(IIS.Sonya_7.Товары));
                }
            }
        }
    }
}
