//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya_7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Финансисты.
    /// </summary>
    // *** Start programmer edit section *** (Финансисты CustomAttributes)

    // *** End programmer edit section *** (Финансисты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФинансистыE", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "НомерТелефона as \'Номер телефона\'"})]
    [View("ФинансистыL", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "НомерТелефона as \'Номер телефона\'"})]
    public class Финансисты : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fФИО;
        
        private System.DateTime fДатаРождения;
        
        private int fНомерТелефона;
        
        // *** Start programmer edit section *** (Финансисты CustomMembers)

        // *** End programmer edit section *** (Финансисты CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Финансисты.ID CustomAttributes)

        // *** End programmer edit section *** (Финансисты.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Финансисты.ID Get start)

                // *** End programmer edit section *** (Финансисты.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Финансисты.ID Get end)

                // *** End programmer edit section *** (Финансисты.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Финансисты.ID Set start)

                // *** End programmer edit section *** (Финансисты.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Финансисты.ID Set end)

                // *** End programmer edit section *** (Финансисты.ID Set end)
            }
        }
        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Финансисты.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Финансисты.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Финансисты.ДатаРождения Get start)

                // *** End programmer edit section *** (Финансисты.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Финансисты.ДатаРождения Get end)

                // *** End programmer edit section *** (Финансисты.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Финансисты.ДатаРождения Set start)

                // *** End programmer edit section *** (Финансисты.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Финансисты.ДатаРождения Set end)

                // *** End programmer edit section *** (Финансисты.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (Финансисты.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (Финансисты.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (Финансисты.НомерТелефона Get start)

                // *** End programmer edit section *** (Финансисты.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (Финансисты.НомерТелефона Get end)

                // *** End programmer edit section *** (Финансисты.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Финансисты.НомерТелефона Set start)

                // *** End programmer edit section *** (Финансисты.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (Финансисты.НомерТелефона Set end)

                // *** End programmer edit section *** (Финансисты.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Финансисты.ФИО CustomAttributes)

        // *** End programmer edit section *** (Финансисты.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Финансисты.ФИО Get start)

                // *** End programmer edit section *** (Финансисты.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Финансисты.ФИО Get end)

                // *** End programmer edit section *** (Финансисты.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Финансисты.ФИО Set start)

                // *** End programmer edit section *** (Финансисты.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Финансисты.ФИО Set end)

                // *** End programmer edit section *** (Финансисты.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФинансистыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФинансистыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФинансистыE", typeof(IIS.Sonya_7.Финансисты));
                }
            }
            
            /// <summary>
            /// "ФинансистыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФинансистыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФинансистыL", typeof(IIS.Sonya_7.Финансисты));
                }
            }
        }
    }
}
